20/06/2025 12:57:29 Error: thread 2: 1/398; address: улица Мира, 5
 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))20/06/2025 12:57:35 Error: thread 2: 2/398; address: улица Мира, 5
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f5250>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:57:40 Error: thread 2: 3/398; address: улица Мира, 5
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4197ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:57:46 Error: thread 2: 4/398; address: улица Мира, 59
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615e50>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:57:52 Error: thread 2: 5/398; address: улица Мира, 62
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615160>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:57:58 Error: thread 2: 6/398; address: улица Мира, 62
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f4d10>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:58:03 Error: thread 2: 7/398; address: улица Мира, 64
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41442f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:58:09 Error: thread 2: 8/398; address: улица Мира, 94
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d0bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:58:15 Error: thread 2: 9/398; address: улица Мира, 94
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb412d580>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:58:20 Error: thread 2: 10/398; address: улица Мира, 94
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:58:26 Error: thread 2: 11/398; address: улица Мира, 94
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457f7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:58:32 Error: thread 2: 12/398; address: улица Мира, 94
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457c890>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:58:37 Error: thread 2: 13/398; address: улица Мира, 94
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d3da0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:58:43 Error: thread 2: 14/398; address: улица Мира, 94
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e4e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:58:49 Error: thread 2: 15/398; address: улица Мира, 94
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457f920>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:58:55 Error: thread 2: 16/398; address: улица Мира, 94
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:59:01 Error: thread 2: 17/398; address: улица Мира, 94
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60c170>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:59:07 Error: thread 2: 18/398; address: улица Мира, 94
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb412e240>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:59:13 Error: thread 2: 19/398; address: улица Мира, 94
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60c2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:59:19 Error: thread 2: 20/398; address: улица Мира, 2/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41976b0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:59:24 Error: thread 2: 21/398; address: улица Мира, 2/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f6450>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:59:30 Error: thread 2: 22/398; address: улица Мира, 2/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615400>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:59:35 Error: thread 2: 23/398; address: улица Мира, 2/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:59:41 Error: thread 2: 24/398; address: улица Мира, 100
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41441a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:59:47 Error: thread 2: 25/398; address: улица Мира, 100
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4195ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:59:53 Error: thread 2: 26/398; address: улица Мира, 108
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457e360>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 12:59:58 Error: thread 2: 27/398; address: улица Мира, 116
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f4470>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:00:04 Error: thread 2: 28/398; address: улица Мира, 116
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb412ca40>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:00:10 Error: thread 2: 29/398; address: улица Мира, 124
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41455e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:00:16 Error: thread 2: 30/398; address: улица Мира, 124
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457d340>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:00:22 Error: thread 2: 31/398; address: улица Мира, 126
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4146f30>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:00:27 Error: thread 2: 32/398; address: улица Мира, 126
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4147680>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:00:33 Error: thread 2: 33/398; address: улица Мира, 126
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4147620>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:00:39 Error: thread 2: 34/398; address: улица Мира, 93
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:00:45 Error: thread 2: 35/398; address: улица Мира, 100А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41941d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:00:51 Error: thread 2: 36/398; address: улица Мира, 100А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4146ba0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:00:56 Error: thread 2: 37/398; address: улица Мира, 100А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457c830>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:01:02 Error: thread 2: 38/398; address: улица Мира, 100А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457ecf0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:01:08 Error: thread 2: 39/398; address: улица Мира, 100А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144e60>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:01:14 Error: thread 2: 40/398; address: улица Мира, 100А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60dca0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:01:19 Error: thread 2: 41/398; address: улица Мира, 100А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d1700>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:01:25 Error: thread 2: 42/398; address: улица Мира, 100А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457c680>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:01:31 Error: thread 2: 43/398; address: улица Мира, 122А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457f290>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:01:37 Error: thread 2: 44/398; address: улица Миронова, 58
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617740>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:01:43 Error: thread 2: 45/398; address: улица Миронова, 3
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f4830>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:01:49 Error: thread 2: 46/398; address: улица Миронова, 56
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457d340>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:01:54 Error: thread 2: 47/398; address: улица Миронова, 56
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd45a4740>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:02:00 Error: thread 2: 48/398; address: улица Миронова, 56
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb412ff80>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:02:06 Error: thread 2: 49/398; address: улица Миронова, 56
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41455e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:02:12 Error: thread 2: 50/398; address: улица Миронова, 56
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4194bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:02:18 Error: thread 2: 51/398; address: улица Миронова, 56
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41442f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:02:24 Error: thread 2: 52/398; address: переулок Мичурина, 10
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41476b0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:02:29 Error: thread 2: 53/398; address: улица Мичурина, 7
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457c4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:02:35 Error: thread 2: 54/398; address: улица Мичурина, 7
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb412c3e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:02:41 Error: thread 2: 55/398; address: улица Мичурина, 7/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457e330>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:02:46 Error: thread 2: 56/398; address: улица Мичурина, 7/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615490>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:02:52 Error: thread 2: 57/398; address: улица Мичурина, 7/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41472c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:02:58 Error: thread 2: 58/398; address: улица Мичурина, 7/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457c3b0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:03:04 Error: thread 2: 59/398; address: улица Мичурина, 8
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd5813740>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:03:10 Error: thread 2: 60/398; address: улица Можайского, 1А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f6b40>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:03:16 Error: thread 2: 61/398; address: улица Можайского, 1А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4194110>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:03:21 Error: thread 2: 62/398; address: улица Можайского, 2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457f7a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:03:27 Error: thread 2: 63/398; address: улица Можайского, 2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457e450>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:03:33 Error: thread 2: 64/398; address: улица Можайского, 2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617980>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:03:38 Error: thread 2: 65/398; address: улица Можайского, 2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457c2c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:03:44 Error: thread 2: 66/398; address: улица Можайского, 2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41454f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:03:50 Error: thread 2: 67/398; address: улица Можайского, 2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4197ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:03:56 Error: thread 2: 68/398; address: улица Можайского, 2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4146ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:04:01 Error: thread 2: 69/398; address: улица Можайского, 2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615910>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:04:07 Error: thread 2: 70/398; address: улица Можайского, 3/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f230>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:04:13 Error: thread 2: 71/398; address: улица Можайского, 3/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145f70>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:04:18 Error: thread 2: 72/398; address: улица Можайского, 3/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d1070>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:04:24 Error: thread 2: 73/398; address: улица Можайского, 3/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41949e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:04:30 Error: thread 2: 74/398; address: улица Можайского, 3/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4195580>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:04:35 Error: thread 2: 75/398; address: улица Можайского, 3/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145a90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:04:41 Error: thread 2: 76/398; address: улица Можайского, 3/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f7a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:04:47 Error: thread 2: 77/398; address: улица Можайского, 3/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd5844500>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:04:53 Error: thread 2: 78/398; address: улица Можайского, 3/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:04:59 Error: thread 2: 79/398; address: улица Можайского, 3/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4149af0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:01 Error: thread 4: 29/398; address: улица Декабрьских Событий, 102
 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))20/06/2025 13:05:05 Error: thread 2: 80/398; address: улица Можайского, 3/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4149850>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:07 Error: thread 4: 30/398; address: улица Декабрьских Событий, 123
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4148740>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:10 Error: thread 2: 81/398; address: улица Можайского, 3/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb414b5c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:12 Error: thread 4: 31/398; address: улица Декабрьских Событий, 123
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4148530>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:16 Error: thread 2: 82/398; address: улица Можайского, 3/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd457e330>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:18 Error: thread 4: 32/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4197110>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:22 Error: thread 2: 83/398; address: улица Можайского, 3/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb414b560>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:24 Error: thread 4: 33/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145d00>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:28 Error: thread 2: 84/398; address: улица Можайского, 4
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f5c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:30 Error: thread 4: 34/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4195400>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:34 Error: thread 2: 85/398; address: улица Можайского, 6А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4146cc0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:35 Error: thread 4: 35/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145160>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:39 Error: thread 2: 86/398; address: Молодёжная улица, 13
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6157f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:41 Error: thread 4: 36/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:45 Error: thread 2: 87/398; address: Молодёжная улица, 23
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd5786300>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:47 Error: thread 4: 37/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617b00>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:51 Error: thread 2: 88/398; address: улица Молчанова-Сибирского, 43
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f616f90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:53 Error: thread 4: 38/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615d00>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:57 Error: thread 2: 89/398; address: улица Молчанова-Сибирского, 50
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f614890>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:05:58 Error: thread 4: 39/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615640>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:02 Error: thread 2: 90/398; address: переулок МОПРа, 1А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f75c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:04 Error: thread 4: 40/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d0860>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:08 Error: thread 2: 91/398; address: переулок МОПРа, 3
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d1550>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:10 Error: thread 4: 41/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6162d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:14 Error: thread 2: 92/398; address: переулок МОПРа, 3
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4146030>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:16 Error: thread 4: 42/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6142c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:19 Error: thread 2: 93/398; address: переулок МОПРа, 3
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:21 Error: thread 4: 43/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d3bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:25 Error: thread 2: 94/398; address: переулок МОПРа, 5
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41476e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:27 Error: thread 4: 44/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d3800>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:31 Error: thread 2: 95/398; address: переулок МОПРа, 5
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6170b0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:33 Error: thread 4: 45/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:37 Error: thread 2: 96/398; address: переулок МОПРа, 6
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41444a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:38 Error: thread 4: 46/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60d2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:43 Error: thread 2: 97/398; address: переулок МОПРа, 6
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4146c60>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:44 Error: thread 4: 47/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f616870>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:49 Error: thread 2: 98/398; address: Морской проезд, 25
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60db20>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:50 Error: thread 4: 48/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144890>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:55 Error: thread 2: 99/398; address: улица Моцарта, 27
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d23c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:06:55 Error: thread 4: 49/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60c620>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:00 Error: thread 2: 100/398; address: улица Муравьёва, 10А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f736840>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:01 Error: thread 4: 50/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f4140>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:06 Error: thread 2: 101/398; address: улица Муравьёва, 10А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f616f60>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:07 Error: thread 4: 51/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617320>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:12 Error: thread 2: 102/398; address: улица Муравьёва, 10А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4147590>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:13 Error: thread 4: 52/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:18 Error: thread 2: 103/398; address: улица Муравьёва, 2/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd45a40b0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:19 Error: thread 4: 53/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4147a70>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:24 Error: thread 2: 104/398; address: улица Муравьёва, 4
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d3320>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:24 Error: thread 4: 54/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145d30>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:29 Error: thread 2: 105/398; address: улица Муравьёва, 4
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617500>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:30 Error: thread 4: 55/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d0d70>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:35 Error: thread 2: 106/398; address: улица Муравьёва, 8/6
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4147b30>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:36 Error: thread 4: 56/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f7740>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:41 Error: thread 2: 107/398; address: улица Муравьёва, 13
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6151f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:42 Error: thread 4: 57/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d02f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:47 Error: thread 2: 108/398; address: улица Муравьёва, 13
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60fc80>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:48 Error: thread 4: 58/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615970>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:53 Error: thread 2: 109/398; address: улица Муравьёва, 13
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f6fc0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:53 Error: thread 4: 59/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4146cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:59 Error: thread 2: 110/398; address: улица Муравьёва, 13
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f737050>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:07:59 Error: thread 4: 60/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f4920>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:04 Error: thread 2: 111/398; address: улица Муравьёва, 13
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f7740>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:05 Error: thread 4: 61/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e0f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:10 Error: thread 2: 112/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f2c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:11 Error: thread 4: 62/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f260>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:16 Error: thread 2: 113/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60eb70>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:16 Error: thread 4: 63/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f080>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:22 Error: thread 2: 114/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60c5c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:22 Error: thread 4: 64/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:28 Error: thread 4: 65/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60ef00>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:28 Error: thread 2: 115/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f320>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:33 Error: thread 4: 66/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:34 Error: thread 2: 116/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60faa0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:39 Error: thread 4: 67/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f6a20>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:39 Error: thread 2: 117/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f616390>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:45 Error: thread 2: 118/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60cbc0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:45 Error: thread 4: 68/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f800>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:50 Error: thread 4: 69/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd4554e30>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:51 Error: thread 2: 119/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60ec90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:56 Error: thread 4: 70/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:08:56 Error: thread 2: 120/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f614290>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:02 Error: thread 2: 121/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615220>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:02 Error: thread 4: 71/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d0770>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:07 Error: thread 2: 122/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd58445c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:08 Error: thread 4: 72/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d38f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:13 Error: thread 2: 123/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615be0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:14 Error: thread 4: 73/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4147bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:19 Error: thread 2: 124/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d38f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:19 Error: thread 4: 74/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144680>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:25 Error: thread 2: 125/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41474d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:25 Error: thread 4: 75/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d0770>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:31 Error: thread 2: 126/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145310>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:31 Error: thread 4: 76/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4146ff0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:36 Error: thread 2: 127/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d0d70>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:36 Error: thread 4: 77/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145040>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:42 Error: thread 4: 78/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd474ddf0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:42 Error: thread 2: 128/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f4470>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:48 Error: thread 4: 79/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d0bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:48 Error: thread 2: 129/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4147620>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:53 Error: thread 4: 80/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f735790>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:54 Error: thread 2: 130/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4147d70>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:59 Error: thread 4: 81/398; address: улица Декабрьских Событий, 125
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60ff20>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:09:59 Error: thread 2: 131/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60d550>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:05 Error: thread 2: 132/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144320>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:05 Error: thread 4: 82/398; address: улица Декабрьских Событий, 77А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e7e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:10 Error: thread 2: 133/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f770>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:11 Error: thread 4: 83/398; address: улица Декабрьских Событий, 77А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615040>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:16 Error: thread 2: 134/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f140>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:16 Error: thread 4: 84/398; address: улица Муравьёва, 3
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e0f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:22 Error: thread 2: 135/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f8c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:22 Error: thread 4: 85/398; address: Мурманская улица, 3
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd45a6f30>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:28 Error: thread 2: 136/398; address: улица Муравьёва, 17
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617d40>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:28 Error: thread 4: 86/398; address: улица Мухиной, 1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60d160>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:33 Error: thread 4: 87/398; address: улица Мухиной, 1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f736870>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:33 Error: thread 2: 137/398; address: Дальневосточная улица, 29/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f734410>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:39 Error: thread 4: 88/398; address: улица Мухиной, 1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41470e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:39 Error: thread 2: 138/398; address: Дальневосточная улица, 29/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41445c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:45 Error: thread 4: 89/398; address: улица Мухиной, 1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f614da0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:45 Error: thread 2: 139/398; address: Дальневосточная улица, 29/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144380>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:51 Error: thread 4: 90/398; address: улица Мухиной, 1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d3290>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:51 Error: thread 2: 140/398; address: Дальневосточная улица, 29/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617b90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:56 Error: thread 4: 91/398; address: улица Мухиной, 1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f614aa0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:10:57 Error: thread 2: 141/398; address: Дальневосточная улица, 29/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f616b70>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:02 Error: thread 4: 92/398; address: улица Мухиной, 1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145040>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:02 Error: thread 2: 142/398; address: Дальневосточная улица, 29/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41465d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:07 Error: thread 4: 93/398; address: улица Мухиной, 1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f735010>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:08 Error: thread 2: 143/398; address: Дальневосточная улица, 29/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6157c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:13 Error: thread 4: 94/398; address: улица Мухиной, 1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e6f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:14 Error: thread 2: 144/398; address: Дальневосточная улица, 29/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f737e60>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:19 Error: thread 4: 95/398; address: улица Мухиной, 1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60cad0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:20 Error: thread 2: 145/398; address: Дальневосточная улица, 29/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f080>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:24 Error: thread 4: 96/398; address: улица Мухиной, 1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4146900>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:25 Error: thread 2: 146/398; address: Дальневосточная улица, 29/3
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f735670>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:30 Error: thread 4: 97/398; address: улица Мухиной, 1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f6930>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:31 Error: thread 2: 147/398; address: Дальневосточная улица, 29/3
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f500>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:36 Error: thread 4: 98/398; address: улица Мухиной, 1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60c2c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:37 Error: thread 2: 148/398; address: Дальневосточная улица, 29/3
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f7560>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:41 Error: thread 4: 99/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e120>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:42 Error: thread 2: 149/398; address: Дальневосточная улица, 29/3
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41468a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:47 Error: thread 4: 100/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f9910>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:48 Error: thread 2: 150/398; address: Дальневосточная улица, 29/3
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f61e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:53 Error: thread 4: 101/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d0ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:54 Error: thread 2: 151/398; address: Дальневосточная улица, 29/3
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8faf30>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:59 Error: thread 4: 102/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f55b0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:11:59 Error: thread 2: 152/398; address: Дальневосточная улица, 29/4
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f736e40>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:05 Error: thread 4: 103/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615220>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:05 Error: thread 2: 153/398; address: Дальневосточная улица, 29/4
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f6930>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:10 Error: thread 4: 104/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d3320>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:11 Error: thread 2: 154/398; address: Дальневосточная улица, 29/4
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f616510>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:16 Error: thread 4: 105/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f4170>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:17 Error: thread 2: 155/398; address: Дальневосточная улица, 29/4
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6178c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:22 Error: thread 4: 106/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd459a450>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:23 Error: thread 2: 156/398; address: Дальневосточная улица, 29/4
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f736f30>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:28 Error: thread 4: 107/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f616630>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:28 Error: thread 2: 157/398; address: Дальневосточная улица, 29/4
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f71a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:34 Error: thread 4: 108/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617350>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:34 Error: thread 2: 158/398; address: Дальневосточная улица, 29/4
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f89e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:39 Error: thread 4: 109/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f7342c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:40 Error: thread 2: 159/398; address: Дальневосточная улица, 29/4
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f614bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:45 Error: thread 4: 110/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60df70>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:46 Error: thread 2: 160/398; address: Дальневосточная улица, 29/4
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617a10>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:51 Error: thread 4: 111/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f8a10>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:52 Error: thread 2: 161/398; address: Дальневосточная улица, 29/4
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f9be0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:57 Error: thread 4: 112/398; address: улица Мухиной, 10
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fa270>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:12:58 Error: thread 2: 162/398; address: Дальневосточная улица, 29/5
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fb950>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:02 Error: thread 4: 113/398; address: улица Мухиной, 10А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f72c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:04 Error: thread 2: 163/398; address: Дальневосточная улица, 29/5
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f4830>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:08 Error: thread 4: 114/398; address: улица Мухиной, 10А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:09 Error: thread 2: 164/398; address: Дальневосточная улица, 29/5
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60d220>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:14 Error: thread 4: 115/398; address: улица Мухиной, 10А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d38f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:15 Error: thread 2: 165/398; address: Дальневосточная улица, 29/5
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f290>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:20 Error: thread 4: 116/398; address: улица Мухиной, 10А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60d8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:21 Error: thread 2: 166/398; address: Дальневосточная улица, 29/5
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fa4e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:26 Error: thread 4: 117/398; address: улица Мухиной, 11
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fa900>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:27 Error: thread 2: 167/398; address: Дальневосточная улица, 29/5
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:31 Error: thread 4: 118/398; address: улица Мухиной, 11
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f9160>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:32 Error: thread 2: 168/398; address: Дальневосточная улица, 106
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6145c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:37 Error: thread 4: 119/398; address: улица Мухиной, 11
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d2870>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:38 Error: thread 2: 169/398; address: Дальневосточная улица, 106
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fb8f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:43 Error: thread 4: 120/398; address: улица Мухиной, 11
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd469b7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:44 Error: thread 2: 170/398; address: Дальневосточная улица, 106
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f7470>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:49 Error: thread 4: 121/398; address: улица Мухиной, 11
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f8320>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:50 Error: thread 2: 171/398; address: Дальневосточная улица, 106
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fa6c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:55 Error: thread 4: 122/398; address: улица Мухиной, 11
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f530>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:13:55 Error: thread 2: 172/398; address: Дальневосточная улица, 106
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f9730>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:00 Error: thread 4: 123/398; address: улица Мухиной, 12
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:01 Error: thread 2: 173/398; address: Дальневосточная улица, 106
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60d520>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:05 Error: thread 3: 63/398; address: улица Декабрьских Событий, 100
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d1160>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:06 Error: thread 4: 124/398; address: улица Мухиной, 12
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fa840>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:07 Error: thread 2: 174/398; address: Дальневосточная улица, 106
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60fa10>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:07 Error: thread 0: 64/398; address: Горная улица, 4
 HTTPConnectionPool(host='localhost', port=33131): Max retries exceeded with url: /session/c743d862c0bed1a7420fd630385ade00/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fa6c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:11 Error: thread 3: 64/398; address: улица Декабрьских Событий, 100
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d1700>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:12 Error: thread 4: 125/398; address: улица Мухиной, 12
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60dbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:12 Error: thread 2: 175/398; address: Дальневосточная улица, 106
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fb500>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:12 Error: thread 0: 65/398; address: Горная улица, 4
 HTTPConnectionPool(host='localhost', port=33131): Max retries exceeded with url: /session/c743d862c0bed1a7420fd630385ade00/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60c050>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:17 Error: thread 3: 65/398; address: улица Декабрьских Событий, 100
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60d760>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:18 Error: thread 4: 126/398; address: улица Мухиной, 13
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8faa50>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:18 Error: thread 2: 176/398; address: Дальневосточная улица, 110
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60faa0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:18 Error: thread 0: 66/398; address: Горная улица, 4
 HTTPConnectionPool(host='localhost', port=33131): Max retries exceeded with url: /session/c743d862c0bed1a7420fd630385ade00/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd5844e90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:22 Error: thread 3: 66/398; address: улица Декабрьских Событий, 100
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f80e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:23 Error: thread 4: 127/398; address: улица Мухиной, 13
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f9a00>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:24 Error: thread 2: 177/398; address: Дальневосточная улица, 110
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f736f30>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:24 Error: thread 0: 67/398; address: Горная улица, 4
 HTTPConnectionPool(host='localhost', port=33131): Max retries exceeded with url: /session/c743d862c0bed1a7420fd630385ade00/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd469b7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:28 Error: thread 3: 67/398; address: улица Декабрьских Событий, 100
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f9b20>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:29 Error: thread 4: 128/398; address: улица Мухиной, 13
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60d310>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:29 Error: thread 0: 68/398; address: Горная улица, 4
 HTTPConnectionPool(host='localhost', port=33131): Max retries exceeded with url: /session/c743d862c0bed1a7420fd630385ade00/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f8350>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:29 Error: thread 2: 178/398; address: Дальневосточная улица, 110
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f7354c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:34 Error: thread 3: 68/398; address: улица Декабрьских Событий, 100
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f734b90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:35 Error: thread 2: 179/398; address: Дальневосточная улица, 110
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f8260>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:35 Error: thread 0: 69/398; address: Горная улица, 4
 HTTPConnectionPool(host='localhost', port=33131): Max retries exceeded with url: /session/c743d862c0bed1a7420fd630385ade00/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f737ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:35 Error: thread 4: 129/398; address: улица Мухиной, 13А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f2f30>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:39 Error: thread 3: 69/398; address: улица Декабрьских Событий, 100
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f9e20>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:41 Error: thread 2: 180/398; address: Дальневосточная улица, 110
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615730>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:41 Error: thread 0: 70/398; address: Горная улица, 4
 HTTPConnectionPool(host='localhost', port=33131): Max retries exceeded with url: /session/c743d862c0bed1a7420fd630385ade00/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4147230>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:41 Error: thread 4: 130/398; address: улица Мухиной, 17/1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4146b10>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:45 Error: thread 3: 70/398; address: улица Декабрьских Событий, 78
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f92e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:46 Error: thread 2: 181/398; address: Дальневосточная улица, 112
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f734f80>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:47 Error: thread 4: 131/398; address: улица Мухиной, 17/1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f7355e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:51 Error: thread 3: 71/398; address: улица Декабрьских Событий, 78
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f736de0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:52 Error: thread 2: 182/398; address: Дальневосточная улица, 112
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd45a05c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:53 Error: thread 4: 132/398; address: улица Мухиной, 19
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd5813590>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:57 Error: thread 3: 72/398; address: улица Декабрьских Событий, 78
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f3260>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:58 Error: thread 2: 183/398; address: Дальневосточная улица, 112
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f735310>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:14:58 Error: thread 4: 133/398; address: улица Мухиной, 19А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f736f60>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:03 Error: thread 3: 73/398; address: улица Декабрьских Событий, 78
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fb1a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:04 Error: thread 2: 184/398; address: Дальневосточная улица, 112
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd5811b50>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:04 Error: thread 4: 134/398; address: улица Мухиной, 19А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144950>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:08 Error: thread 3: 74/398; address: улица Декабрьских Событий, 78
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f3260>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:10 Error: thread 2: 185/398; address: Дальневосточная улица, 112
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f734950>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:10 Error: thread 4: 135/398; address: улица Мухиной, 19А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4147b90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:14 Error: thread 3: 75/398; address: улица Декабрьских Событий, 78
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f7369f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:15 Error: thread 2: 186/398; address: Дальневосточная улица, 112
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fa270>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:16 Error: thread 4: 136/398; address: улица Мухиной, 19А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4146210>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:19 Error: thread 3: 76/398; address: улица Декабрьских Событий, 78
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f3320>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:21 Error: thread 2: 187/398; address: Дальневосточная улица, 112
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f737470>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:21 Error: thread 4: 137/398; address: улица Мухиной, 19Б
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e990>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:25 Error: thread 3: 77/398; address: улица Декабрьских Событий, 78
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f735310>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:27 Error: thread 2: 188/398; address: Дальневосточная улица, 112
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f9d60>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:27 Error: thread 4: 138/398; address: улица Мухиной, 19Б
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e840>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:31 Error: thread 3: 78/398; address: улица Декабрьских Событий, 72/1
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f1340>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:32 Error: thread 2: 189/398; address: Дальневосточная улица, 22/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f736690>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:33 Error: thread 4: 139/398; address: улица Мухиной, 19Б
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60cb90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:37 Error: thread 3: 79/398; address: улица Декабрьских Событий, 100А
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f23c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:38 Error: thread 2: 190/398; address: Дальневосточная улица, 22/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6161e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:38 Error: thread 4: 140/398; address: улица Мухиной, 19Б
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e420>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:43 Error: thread 3: 80/398; address: улица Декабрьских Событий, 100А
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f614a40>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:44 Error: thread 2: 191/398; address: Дальневосточная улица, 22/2
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617650>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:44 Error: thread 4: 141/398; address: улица Мухиной, 19Б
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd45a5970>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:48 Error: thread 3: 81/398; address: улица Декабрьских Событий, 100А
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f616bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:50 Error: thread 4: 142/398; address: улица Мухиной, 19Б
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f616b70>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:50 Error: thread 2: 192/398; address: Дальневосточная улица, 22/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f49e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:54 Error: thread 3: 82/398; address: улица Декабрьских Событий, 100А
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f67e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:56 Error: thread 2: 193/398; address: Дальневосточная улица, 22/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4147890>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:56 Error: thread 4: 143/398; address: улица Мухиной, 19Б
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41448c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:15:59 Error: thread 3: 83/398; address: улица Декабрьских Событий, 100А
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f4050>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:02 Error: thread 2: 194/398; address: Дальневосточная улица, 22/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:02 Error: thread 4: 144/398; address: улица Мухиной, 2/1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144da0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:05 Error: thread 3: 84/398; address: улица Декабрьских Событий, 21
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41458e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:07 Error: thread 2: 195/398; address: Дальневосточная улица, 22/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f5a90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:08 Error: thread 4: 145/398; address: улица Мухиной, 2/1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768ccc79c830>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:11 Error: thread 3: 85/398; address: улица Декабрьских Событий, 21
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd58451c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:13 Error: thread 2: 196/398; address: Дальневосточная улица, 22/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144680>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:14 Error: thread 4: 146/398; address: улица Мухиной, 20/1
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615070>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:17 Error: thread 3: 86/398; address: улица Декабрьских Событий, 21
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144d70>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:18 Error: thread 2: 197/398; address: Дальневосточная улица, 22/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f4cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:19 Error: thread 4: 147/398; address: улица Мухиной, 25
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6177a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:23 Error: thread 3: 87/398; address: улица Декабрьских Событий, 23
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd5844bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:24 Error: thread 2: 198/398; address: Дальневосточная улица, 55
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4146150>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:25 Error: thread 4: 148/398; address: улица Мухиной, 2А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6161e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:29 Error: thread 3: 88/398; address: улица Декабрьских Событий, 23
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd5844e90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:30 Error: thread 2: 199/398; address: Дальневосточная улица, 55
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:31 Error: thread 4: 149/398; address: улица Мухиной, 2А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f2f60>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:34 Error: thread 3: 89/398; address: улица Декабрьских Событий, 23
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9efd4110>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:36 Error: thread 2: 200/398; address: Дальневосточная улица, 55
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f735010>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:36 Error: thread 4: 150/398; address: улица Мухиной, 2А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145310>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:40 Error: thread 3: 90/398; address: улица Декабрьских Событий, 23
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f737e60>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:41 Error: thread 2: 201/398; address: Дальневосточная улица, 55А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60da00>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:42 Error: thread 4: 151/398; address: улица Мухиной, 2А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60cf20>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:46 Error: thread 3: 91/398; address: улица Декабрьских Событий, 23А
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f734440>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:47 Error: thread 2: 202/398; address: Дальневосточная улица, 57
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60c9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:48 Error: thread 4: 152/398; address: улица Мухиной, 2А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e360>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:52 Error: thread 3: 92/398; address: улица Декабрьских Событий, 3
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f734440>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:53 Error: thread 2: 203/398; address: Дальневосточная улица, 61А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60d2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:54 Error: thread 4: 153/398; address: улица Мухиной, 2А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f99a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:57 Error: thread 3: 93/398; address: улица Декабрьских Событий, 3
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f736cc0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:16:58 Error: thread 2: 204/398; address: Дальневосточная улица, 67
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f7340e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:00 Error: thread 4: 154/398; address: улица Мухиной, 2А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f8080>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:03 Error: thread 3: 94/398; address: улица Декабрьских Событий, 34
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f7362d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:04 Error: thread 2: 205/398; address: Дальневосточная улица, 67А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f7369f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:05 Error: thread 4: 155/398; address: улица Мухиной, 2А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60df10>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:09 Error: thread 3: 95/398; address: улица Декабрьских Событий, 34
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f734c50>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:09 Error: thread 2: 206/398; address: Дальневосточная улица, 67А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fae10>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:11 Error: thread 4: 156/398; address: улица Мухиной, 2А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e360>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:15 Error: thread 3: 96/398; address: улица Декабрьских Событий, 44
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f736060>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:15 Error: thread 2: 207/398; address: Дальневосточная улица, 67А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60cd40>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:17 Error: thread 4: 157/398; address: улица Мухиной, 2А
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d0b30>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:20 Error: thread 3: 97/398; address: улица Декабрьских Событий, 44
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f7341d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:21 Error: thread 2: 208/398; address: Дальневосточная улица, 67А
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fa000>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:23 Error: thread 4: 158/398; address: улица Мухиной, 2В
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd4752c90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:26 Error: thread 3: 98/398; address: улица Декабрьских Событий, 44
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8faed0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:27 Error: thread 2: 209/398; address: Дальневосточная улица, 69
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f736ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:29 Error: thread 4: 159/398; address: улица Мухиной, 2В
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd45a4830>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:32 Error: thread 3: 99/398; address: улица Декабрьских Событий, 44
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f735700>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:32 Error: thread 2: 210/398; address: Дальневосточная улица, 69
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f6ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:34 Error: thread 4: 160/398; address: улица Мухиной, 2В
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6151f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:38 Error: thread 3: 100/398; address: улица Декабрьских Событий, 44
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8fa000>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:38 Error: thread 2: 211/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615e20>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:40 Error: thread 4: 161/398; address: улица Мухиной, 2В
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f616e40>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:44 Error: thread 3: 101/398; address: улица Декабрьских Событий, 44
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6156d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:44 Error: thread 2: 212/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd5811b50>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:46 Error: thread 4: 162/398; address: улица Мухиной, 2В
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f734d40>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:49 Error: thread 3: 102/398; address: улица Декабрьских Событий, 44
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f8a10>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:50 Error: thread 2: 213/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f614e00>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:52 Error: thread 4: 163/398; address: улица Мухиной, 2Е
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145af0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:55 Error: thread 3: 103/398; address: улица Декабрьских Событий, 44
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd5844e90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:55 Error: thread 2: 214/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f737d40>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:17:58 Error: thread 4: 164/398; address: улица Мухиной, 2Е
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145a90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:01 Error: thread 3: 104/398; address: улица Декабрьских Событий, 44
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f9fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:01 Error: thread 2: 215/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617590>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:04 Error: thread 4: 165/398; address: улица Мухиной, 3
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145f40>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:06 Error: thread 3: 105/398; address: улица Декабрьских Событий, 44
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6144a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:07 Error: thread 2: 216/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60ff20>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:10 Error: thread 4: 166/398; address: улица Мухиной, 9
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44f6150>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:12 Error: thread 3: 106/398; address: улица Декабрьских Событий, 44
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144c80>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:13 Error: thread 2: 217/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145580>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:15 Error: thread 4: 167/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd5844bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:18 Error: thread 3: 107/398; address: улица Декабрьских Событий, 62
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41459a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:18 Error: thread 2: 218/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6161e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:21 Error: thread 4: 168/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f617170>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:24 Error: thread 3: 108/398; address: улица Декабрьских Событий, 62
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4144da0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:24 Error: thread 2: 219/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f6141a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:27 Error: thread 4: 169/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f614650>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:29 Error: thread 3: 109/398; address: улица Декабрьских Событий, 62
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4145d00>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:30 Error: thread 2: 220/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f736450>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:33 Error: thread 4: 170/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f980>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:35 Error: thread 3: 110/398; address: улица Декабрьских Событий, 62
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd4752c90>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:36 Error: thread 2: 221/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd41f8770>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:38 Error: thread 4: 171/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f616a50>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:41 Error: thread 3: 111/398; address: улица Декабрьских Событий, 74А
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768ccc7707a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:42 Error: thread 2: 222/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4146390>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:44 Error: thread 4: 172/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41468a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:47 Error: thread 3: 112/398; address: улица Декабрьских Событий, 74А
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd47523f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:47 Error: thread 2: 223/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41448f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:50 Error: thread 4: 173/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60d400>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:52 Error: thread 3: 113/398; address: улица Декабрьских Событий, 74А
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd58138f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:53 Error: thread 2: 224/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d28d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:56 Error: thread 4: 174/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f4a0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:58 Error: thread 3: 114/398; address: улица Декабрьских Событий, 82
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd58138f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:18:58 Error: thread 2: 225/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768ccc3e5610>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:01 Error: thread 4: 175/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f736270>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:04 Error: thread 3: 115/398; address: улица Декабрьских Событий, 82
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd58124e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:04 Error: thread 2: 226/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d17c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:07 Error: thread 4: 176/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f737e00>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:09 Error: thread 3: 116/398; address: улица Декабрьских Событий, 82
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd469b7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:10 Error: thread 2: 227/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb4147740>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:13 Error: thread 4: 177/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f87d0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:15 Error: thread 3: 117/398; address: улица Декабрьских Событий, 84/1
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd58135f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:16 Error: thread 2: 228/398; address: Дальневосточная улица, 110/1
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f7346e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:19 Error: thread 4: 178/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb41979b0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:21 Error: thread 3: 118/398; address: улица Декабрьских Событий, 88
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd45a5430>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:21 Error: thread 2: 229/398; address: Дальневосточная улица, 114
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f7357f0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:24 Error: thread 4: 179/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cb44d21e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:27 Error: thread 3: 119/398; address: улица Декабрьских Событий, 88
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768ccc700bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:27 Error: thread 2: 230/398; address: Дальневосточная улица, 114
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f615310>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:30 Error: thread 4: 180/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f8bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:32 Error: thread 3: 120/398; address: улица Декабрьских Событий, 88
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60f2c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:32 Error: thread 2: 231/398; address: Дальневосточная улица, 116
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e030>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:36 Error: thread 4: 181/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768cd5811b50>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:38 Error: thread 2: 232/398; address: Дальневосточная улица, 116
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e0c0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:38 Error: thread 3: 121/398; address: улица Декабрьских Событий, 88
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60e450>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:41 Error: thread 4: 182/398; address: улица Мухиной, 8
 HTTPConnectionPool(host='localhost', port=49019): Max retries exceeded with url: /session/9acc1711866022532a345b95a9f5a0dc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9e8f9fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:44 Error: thread 2: 233/398; address: Дальневосточная улица, 116
 HTTPConnectionPool(host='localhost', port=53491): Max retries exceeded with url: /session/5efa2214a09d3c6ee5317130088365dd/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f60c6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))20/06/2025 13:19:44 Error: thread 3: 122/398; address: улица Декабрьских Событий, 88
 HTTPConnectionPool(host='localhost', port=60013): Max retries exceeded with url: /session/8650ce225ea5cee347c6b216401312b9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x768c9f737d40>: Failed to establish a new connection: [Errno 111] Connection refused'))